name: Deploy Static Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Stap 1: Checkout de code
      - name: Checkout code
        uses: actions/checkout@v3

      # Stap 2: Installeer Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Stap 3: Installeren van Poetry
      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          export PATH="$HOME/.local/bin:$PATH"

      # Stap 4: Configureer Poetry om Python 3.11 te gebruiken
      - name: Configure Poetry to use Python 3.11
        run: |
          poetry env use python3.11

      # Stap 5: Installeren van de afhankelijkheden
      - name: Install dependencies
        run: |
          poetry install

      # Stap 6: Oryx build voor static web app
      - name: Build app with Oryx
        run: |
          curl -sSL https://github.com/Microsoft/Oryx/releases/download/v0.2.20241003.1/oryx-linux-x64.tar.gz | tar -xz
          ./oryx-linux-x64/bin/oryx build --platform python --platform-version 3.11 --output /github/workspace/_build

      # Stap 7: Deploy de applicatie naar Azure
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
