name: Deploy to Azure Static Web App

on:
  push:
    branches:
      - main  # Of de branch waar je de deploy naar wilt triggeren

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout de code
      - name: Checkout code
        uses: actions/checkout@v3

      # Installeer Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      # Zet de juiste Python versie (3.11 in dit geval)
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies via Poetry
      - name: Install dependencies
        run: |
          poetry install

      # Build en deploy naar Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
          action: "upload"
          app_location: "/"
          api_location: "api"  # Alleen als je een API hebt, anders leeg laten
          output_location: "build"  # Vul dit in met de locatie van de build output
